[package]
name = "greeter-lambda"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.81"
axum = "0.7.4"
lambda_http = "0.10.0"
lambda_runtime = "0.10.0"
serde = "1.0.197"
serde_json = "1.0.114"
tokio = { version = "1", features = ["macros"] }
tracing-subscriber = "0.3.18"
